-- ============================================
-- CampusDine Database Setup Script
-- Run this script in MySQL Workbench
-- ============================================

-- Step 1: Create the database (if it doesn't exist)
CREATE DATABASE IF NOT EXISTS CampusDine;
USE CampusDine;

-- Step 2: Create all tables

-- Users table
CREATE TABLE IF NOT EXISTS Users (
  userId VARCHAR(255), 
  avatar VARCHAR(255),
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) DEFAULT 'user',
  createdAt VARCHAR(255) NOT NULL, 
  updatedAt VARCHAR(255) NOT NULL,
  PRIMARY KEY (userId)
); 

-- Categories table
CREATE TABLE IF NOT EXISTS Categories (
  categoryId VARCHAR(255) PRIMARY KEY,
  categoryName VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  categoryImage VARCHAR(255),
  createdAt VARCHAR(255) NOT NULL,
  updatedAt VARCHAR(255) NOT NULL
);

-- Products table
CREATE TABLE IF NOT EXISTS Products (
  productId VARCHAR(255) PRIMARY KEY,
  productName VARCHAR(255) NOT NULL,
  image VARCHAR(255) DEFAULT "noImg.png",
  rating INT DEFAULT 0,
  description VARCHAR(255) DEFAULT "No Description",
  vegetarian BOOLEAN NOT NULL,
  price INT NOT NULL,
  categoryId VARCHAR(255) NOT NULL,
  createdAt VARCHAR(255) NOT NULL,
  updatedAt VARCHAR(255) NOT NULL,
  FOREIGN KEY (categoryId) REFERENCES Categories(categoryId) ON DELETE CASCADE ON UPDATE CASCADE 
); 

-- Orders table
CREATE TABLE IF NOT EXISTS Orders (
  orderId VARCHAR(255) PRIMARY KEY, 
  userId VARCHAR(255) NOT NULL,
  orderNumber BIGINT UNIQUE AUTO_INCREMENT, 
  pickUpTime VARCHAR(255) NOT NULL,
  expiryDate VARCHAR(255) NOT NULL,
  total INT NOT NULL,
  createdAt VARCHAR(255) NOT NULL,
  updatedAt VARCHAR(255) NOT NULL,
  FOREIGN KEY (userId) REFERENCES Users(userId) ON DELETE CASCADE ON UPDATE CASCADE
); 

-- OrderItems table
CREATE TABLE IF NOT EXISTS OrderItems (
  orderItemsId VARCHAR(255) PRIMARY KEY,
  orderId VARCHAR(255) NOT NULL, 
  productId VARCHAR(255) NOT NULL, 
  quantity INT DEFAULT 1, 
  subtotal INT NOT NULL, 
  createdAt VARCHAR(255) NOT NULL, 
  updatedAt VARCHAR(255) NOT NULL, 
  FOREIGN KEY (orderId) REFERENCES Orders(orderId) ON DELETE CASCADE ON UPDATE CASCADE, 
  FOREIGN KEY (productId) REFERENCES Products(productId) ON DELETE CASCADE ON UPDATE CASCADE
); 

-- OrderStatus table
CREATE TABLE IF NOT EXISTS OrderStatus (
  orderStatusId VARCHAR(255) PRIMARY KEY,
  orderId VARCHAR(255) NOT NULL,
  status ENUM ('processing', 'placed', 'ready', 'delivered', 'cancelled', 'expired') DEFAULT 'processing', 
  createdAt VARCHAR(255) NOT NULL,
  updatedAt VARCHAR(255) NOT NULL,
  FOREIGN KEY (orderId) REFERENCES Orders(orderId) ON DELETE CASCADE ON UPDATE CASCADE
); 

-- Step 3: Insert sample categories
-- Note: categoryId will be generated by the application when categories are created through the API
-- These are optional sample categories. You can add them later through the admin panel.
-- If you want to insert them now, uncomment and modify the UUIDs below:

/*
INSERT INTO Categories (categoryId, categoryName, description, categoryImage, createdAt, updatedAt)
VALUES
(REPLACE(UUID(), '-', ''), 'All', 'All available food item', 'noCategory.png', CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR), CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR)),
(REPLACE(UUID(), '-', ''), 'NonVeg', 'Non Vegetarian dishes', 'noCategory.png', CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR), CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR)),
(REPLACE(UUID(), '-', ''), 'Chinese', 'Chinese dishes', 'noCategory.png', CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR), CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR)),
(REPLACE(UUID(), '-', ''), 'Salads', 'Fresh and healthy salads', 'noCategory.png', CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR), CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR)),
(REPLACE(UUID(), '-', ''), 'Meals', 'Complete meals', 'noCategory.png', CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR), CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR)),
(REPLACE(UUID(), '-', ''), 'Veg', 'Vegetarian dishes', 'noCategory.png', CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR), CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR)),
(REPLACE(UUID(), '-', ''), 'Beverages', 'Refreshing Beverages', 'noCategory.png', CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR), CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR)),
(REPLACE(UUID(), '-', ''), 'Snacks', 'Snack items', 'noCategory.png', CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR), CAST(UNIX_TIMESTAMP(NOW()) * 1000 AS CHAR));
*/

-- Verify tables were created
SELECT 'Database setup completed successfully!' AS Status;
SELECT COUNT(*) AS 'Number of Tables Created' 
FROM information_schema.tables 
WHERE table_schema = 'CampusDine';

-- Show all tables
SHOW TABLES;

